# Generated by Django 3.2.18 on 2023-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230221_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='direction',
            field=models.CharField(max_length=1),
        ),
    ]
